apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: cnrn-system
spec:
  googleServiceAccount: "gkeupdatetriger@symmetric-ion-423517-n3.iam.gserviceaccount.com"
